// <auto-generated />
using System;
using FarmManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmManagement.API.Migrations
{
    [DbContext(typeof(FarmDbContext))]
    partial class FarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmManagement.API.Models.AssetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetItems");
                });

            modelBuilder.Entity("FarmManagement.API.Models.AssetTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetWarehouseItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TargetBarnId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetWarehouseItemId");

                    b.HasIndex("TargetBarnId");

                    b.ToTable("AssetTransactions");
                });

            modelBuilder.Entity("FarmManagement.API.Models.AssetWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId")
                        .IsUnique();

                    b.ToTable("AssetWarehouses");
                });

            modelBuilder.Entity("FarmManagement.API.Models.AssetWarehouseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetItemId")
                        .HasColumnType("int");

                    b.Property<int>("AssetWarehouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("InBarnsQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetItemId");

                    b.HasIndex("AssetWarehouseId");

                    b.ToTable("AssetWarehouseItems");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Barn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Barns");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarnId")
                        .HasColumnType("int");

                    b.Property<int>("ChickAge")
                        .HasColumnType("int");

                    b.Property<int>("ChickCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCulled")
                        .HasColumnType("int");

                    b.Property<int>("TotalMortality")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarnId");

                    b.HasIndex("FarmId");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("FarmManagement.API.Models.DailyFeedConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DailyRecordId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId");

                    b.HasIndex("ItemId");

                    b.ToTable("DailyFeedConsumptions");
                });

            modelBuilder.Entity("FarmManagement.API.Models.DailyMedicineConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DailyRecordId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DailyRecordId");

                    b.HasIndex("ItemId");

                    b.ToTable("DailyMedicineConsumptions");
                });

            modelBuilder.Entity("FarmManagement.API.Models.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChickAge")
                        .HasColumnType("int");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int>("DeadCount")
                        .HasColumnType("int");

                    b.Property<int>("DeadCumulative")
                        .HasColumnType("int");

                    b.Property<int>("RemainingChicks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.ToTable("DailyRecords");
                });

            modelBuilder.Entity("FarmManagement.API.Models.EggProductionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarnId")
                        .HasColumnType("int");

                    b.Property<int>("CartonsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("LiveBirdsCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TotalEggs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarnId");

                    b.HasIndex("CycleId");

                    b.HasIndex("FarmId");

                    b.ToTable("EggProductionRecords");
                });

            modelBuilder.Entity("FarmManagement.API.Models.EggSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TraderId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("EggSales");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("FarmManagement.API.Models.FeedMix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeedTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FeedTypeId");

                    b.ToTable("FeedMixes");
                });

            modelBuilder.Entity("FarmManagement.API.Models.FeedMixDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeedMixId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FeedMixId");

                    b.HasIndex("ItemId");

                    b.ToTable("FeedMixDetails");
                });

            modelBuilder.Entity("FarmManagement.API.Models.FeedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeedTypes");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerTon")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("FarmManagement.API.Models.WarehouseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Withdrawn")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseItems");
                });

            modelBuilder.Entity("FarmManagement.API.Models.WarehouseTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EggProductionRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("EggSaleId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerTon")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TraderId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EggProductionRecordId");

                    b.HasIndex("EggSaleId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TraderId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseTransactions");
                });

            modelBuilder.Entity("FarmManagement.API.Models.AssetTransaction", b =>
                {
                    b.HasOne("FarmManagement.API.Models.AssetWarehouseItem", "AssetWarehouseItem")
                        .WithMany()
                        .HasForeignKey("AssetWarehouseItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Barn", "TargetBarn")
                        .WithMany()
                        .HasForeignKey("TargetBarnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetWarehouseItem");

                    b.Navigation("TargetBarn");
                });

            modelBuilder.Entity("FarmManagement.API.Models.AssetWarehouse", b =>
                {
                    b.HasOne("FarmManagement.API.Models.Farm", "Farm")
                        .WithOne("AssetWarehouse")
                        .HasForeignKey("FarmManagement.API.Models.AssetWarehouse", "FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FarmManagement.API.Models.AssetWarehouseItem", b =>
                {
                    b.HasOne("FarmManagement.API.Models.AssetItem", "AssetItem")
                        .WithMany()
                        .HasForeignKey("AssetItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.AssetWarehouse", "AssetWarehouse")
                        .WithMany("Items")
                        .HasForeignKey("AssetWarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetItem");

                    b.Navigation("AssetWarehouse");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Barn", b =>
                {
                    b.HasOne("FarmManagement.API.Models.Farm", "Farm")
                        .WithMany("Barns")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Cycle", b =>
                {
                    b.HasOne("FarmManagement.API.Models.Barn", "Barn")
                        .WithMany("Cycles")
                        .HasForeignKey("BarnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Farm", "Farm")
                        .WithMany("Cycles")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barn");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FarmManagement.API.Models.DailyFeedConsumption", b =>
                {
                    b.HasOne("FarmManagement.API.Models.DailyRecord", "DailyRecord")
                        .WithMany("FeedConsumptions")
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRecord");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FarmManagement.API.Models.DailyMedicineConsumption", b =>
                {
                    b.HasOne("FarmManagement.API.Models.DailyRecord", "DailyRecord")
                        .WithMany("MedicineConsumptions")
                        .HasForeignKey("DailyRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyRecord");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FarmManagement.API.Models.DailyRecord", b =>
                {
                    b.HasOne("FarmManagement.API.Models.Cycle", "Cycle")
                        .WithMany("DailyRecords")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("FarmManagement.API.Models.EggProductionRecord", b =>
                {
                    b.HasOne("FarmManagement.API.Models.Barn", "Barn")
                        .WithMany("EggProductionRecords")
                        .HasForeignKey("BarnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Cycle", "Cycle")
                        .WithMany("EggProductionRecords")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barn");

                    b.Navigation("Cycle");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FarmManagement.API.Models.EggSale", b =>
                {
                    b.HasOne("FarmManagement.API.Models.Trader", "Trader")
                        .WithMany("EggSales")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trader");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FarmManagement.API.Models.FeedMix", b =>
                {
                    b.HasOne("FarmManagement.API.Models.FeedType", "FeedType")
                        .WithMany("FeedMixes")
                        .HasForeignKey("FeedTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedType");
                });

            modelBuilder.Entity("FarmManagement.API.Models.FeedMixDetail", b =>
                {
                    b.HasOne("FarmManagement.API.Models.FeedMix", "FeedMix")
                        .WithMany("Details")
                        .HasForeignKey("FeedMixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeedMix");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Warehouse", b =>
                {
                    b.HasOne("FarmManagement.API.Models.Farm", "Farm")
                        .WithOne("Warehouse")
                        .HasForeignKey("FarmManagement.API.Models.Warehouse", "FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FarmManagement.API.Models.WarehouseItem", b =>
                {
                    b.HasOne("FarmManagement.API.Models.Item", "Item")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Warehouse", "Warehouse")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FarmManagement.API.Models.WarehouseTransaction", b =>
                {
                    b.HasOne("FarmManagement.API.Models.EggProductionRecord", null)
                        .WithMany("WarehouseTransactions")
                        .HasForeignKey("EggProductionRecordId");

                    b.HasOne("FarmManagement.API.Models.EggSale", "EggSale")
                        .WithMany()
                        .HasForeignKey("EggSaleId");

                    b.HasOne("FarmManagement.API.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmManagement.API.Models.Trader", "Trader")
                        .WithMany("Transactions")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FarmManagement.API.Models.Warehouse", "Warehouse")
                        .WithMany("Transactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EggSale");

                    b.Navigation("Item");

                    b.Navigation("Trader");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FarmManagement.API.Models.AssetWarehouse", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Barn", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("EggProductionRecords");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Cycle", b =>
                {
                    b.Navigation("DailyRecords");

                    b.Navigation("EggProductionRecords");
                });

            modelBuilder.Entity("FarmManagement.API.Models.DailyRecord", b =>
                {
                    b.Navigation("FeedConsumptions");

                    b.Navigation("MedicineConsumptions");
                });

            modelBuilder.Entity("FarmManagement.API.Models.EggProductionRecord", b =>
                {
                    b.Navigation("WarehouseTransactions");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Farm", b =>
                {
                    b.Navigation("AssetWarehouse")
                        .IsRequired();

                    b.Navigation("Barns");

                    b.Navigation("Cycles");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FarmManagement.API.Models.FeedMix", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("FarmManagement.API.Models.FeedType", b =>
                {
                    b.Navigation("FeedMixes");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Item", b =>
                {
                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Trader", b =>
                {
                    b.Navigation("EggSales");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FarmManagement.API.Models.Warehouse", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("WarehouseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
